name: Deploy Website to Azure Web App

# Define when to trigger the workflow
on:
  push:
    branches:
      - main  # Trigger on pushes to the main branch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install Node.js and dependencies
      uses: actions/setup-node@v3
      with:
        node-version: '14'

    - name: Install dependencies
      run: npm install

    - name: Build
      run: npm run build  # Build the React app

    - name: Archive production artifacts
      uses: actions/upload-artifact@v2
      with:
        name: build  # Name of the artifact to be uploaded
        path: build  # Path to the directory containing the build artifacts

  deploy:
    runs-on: ubuntu-latest
    needs: build  # Make sure the 'build' job is completed before starting the 'deploy' job

    steps:
    - name: Download artifact
      uses: actions/download-artifact@v2
      with:
        name: build  # Corrected artifact name

    - name: List Artifact Contents
      run: ls -R ${{ github.workspace }}/build

    - name: Deploy to Azure App Service
      uses: azure/webapps-deploy@v3
      with:
        app-name: 'NodejsApp2024'  # Replace 'your-app-name' with your Azure App Service name
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: ${{ github.workspace }}/build  # Corrected path to the build directory
