name: Deploy Website to Azure Web App

# Define when to trigger the workflow
on:
  push:
    branches:
      - main  # Trigger on pushes to the main branch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Node.js and dependencies
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install dependencies
      run: npm install

    - name: Build
      run: npm run build  # Build the React app

  deploy:
    runs-on: ubuntu-latest
    needs: build  # Make sure the 'build' job is completed before starting the 'deploy' job

    steps:
    - name: Download artifact
      uses: actions/download-artifact@v2
      with:
        name: build  # Download the build artifact from the 'build' job
        path: ./build

    - name: Deploy to Azure App Service
      uses: azure/webapps-deploy@v2  # Use the Azure Web Apps Deploy action
      with:
        app-name: 'NodejsApp2024'  # Replace 'your-app-name' with your Azure App Service name
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}  # Store your Azure App Service publish profile as a secret and reference it here
        package: ./build
